import React from "react";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

export default function Home() {
  return (
    <HomeWrapper>
      <Head>
        <title>BOILERPLATE WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <IssueList>
          <IssueListItem>
            <div className="title-wrapper">
              <h2>규제에 가로막힌 P2E 게임</h2>
              <p>
                국내 첫 P2E(Play to Earn, 돈 버는 게임)인 ‘무한돌파 삼국지
                리버스’의 서비스가 결국 중단됐습니다. '게임을 통해 획득한
                유·무형의 결과물은 환전할 수 없다'라는 현행법 때문인데요.
                업계에서는 블록체인 기술을 타고 P2E가 세계 게임 시장 트렌드가
                되고 있는 상황에서 단순히 사행성을 이유로 사업을 가로막는 건
                시대착오적 규제라고 지적합니다. 어떻게 생각하세요?
              </p>
            </div>
            <div className="comment-wrapper">
              <Link href="/">
                <a>
                  의견 5개 모두보기<span> &gt;</span>
                </a>
              </Link>
              <ul className="comment-list">
                <li>
                  <span className="user-name">하영2</span>
                  사행성 심한 게 게임만 있나 ㅋㅋ
                </li>
              </ul>
            </div>
          </IssueListItem>
        </IssueList>
      </main>
    </HomeWrapper>
  );
}

export const HomeWrapper = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;

  .main {
    padding: 5rem 0;
    width: 750px;
    margin: auto;
  }
`;

const IssueList = styled.ul``;

const IssueListItem = styled.li`
  .title-wrapper {
    background-color: #333;
    color: #fff;
    padding: 50px;
    h2 {
      font-weight: 700;
      font-size: 33px;
      color: #fff;
      margin-bottom: 12px;
    }
    p {
      font-size: 16px;
      line-height: 140%;
      font-weight: 200;
      overflow: hidden;
      text-overflow: ellipsis;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
    }
  }
  .comment-wrapper {
    padding: 35px;
    background-color: #fff;
    a {
      color: #b0b0b0;
      font-weight: 400;
      font-size: 20px;
      border-bottom: 1px solid #e0e0e0;
      margin-bottom: 12px;
      padding-bottom: 20px;
      line-height: 1;
      display: inline-block;
      width: 100%;
      span {
        font-weight: bold;
      }
    }
    .comment-list {
      margin: 15px 0;
      li {
        -webkit-box-orient: vertical;
        word-wrap: break-word;
        overflow: hidden;
        text-overflow: ellipsis;
        .user-name {
          font-weight: 700;
          color: #333;
          margin-right: 15px;
        }
      }
    }
  }
`;
