import React from "react";
import Head from "next/head";
import styled from "styled-components";
import IssueList from "@/func-components/IssueList";

export default function Home() {
  return (
    <HomeWrapper>
      <Head>
        <title>BOILERPLATE WEB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IssueList />
    </HomeWrapper>
  );
}
export const HomeWrapper = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;

  .main {
    padding: 5rem 0;
    width: 750px;
    margin: auto;
  }
`;
